<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regions = [
            // Provinsi NAD Aceh
            ['provinsi' => 'NAD Aceh', 'kota_kabupaten' => [
                'Kabupaten Aceh Barat',
                'Kabupaten Aceh Barat Daya',
                'Kabupaten Aceh Besar',
                'Kabupaten Aceh Jaya',
                'Kabupaten Aceh Selatan',
                'Kabupaten Aceh Singkil',
                'Kabupaten Aceh Tamiang',
                'Kabupaten Aceh Tengah',
                'Kabupaten Aceh Tenggara',
                'Kabupaten Aceh Timur',
                'Kabupaten Aceh Utara',
                'Kabupaten Bener Meriah',
                'Kabupaten Bireuen',
                'Kabupaten Gayo Lues',
                'Kabupaten Nagan Raya',
                'Kabupaten Pidie',
                'Kabupaten Pidie Jaya',
                'Kabupaten Simeulue',
                'Kota Banda Aceh',
                'Kota Langsa',
                'Kota Lhokseumawe',
                'Kota Sabang',
                'Kota Subulussalam',
            ]],

            // Provinsi Sumatera Utara
            ['provinsi' => 'Sumatera Utara', 'kota_kabupaten' => [
                'Kabupaten Asahan',
                'Kabupaten Batubara',
                'Kabupaten Dairi',
                'Kabupaten Deli Serdang',
                'Kabupaten Humbang Hasundutan',
                'Kabupaten Karo',
                'Kabupaten Labuhanbatu',
                'Kabupaten Labuhanbatu Selatan',
                'Kabupaten Labuhanbatu Utara',
                'Kabupaten Langkat',
                'Kabupaten Mandailing Natal',
                'Kabupaten Nias',
                'Kabupaten Nias Barat',
                'Kabupaten Nias Selatan',
                'Kabupaten Nias Utara',
                'Kabupaten Padang Lawas',
                'Kabupaten Padang Lawas Utara',
                'Kabupaten Pakpak Bharat',
                'Kabupaten Samosir',
                'Kabupaten Serdang Bedagai',
                'Kabupaten Simalungun',
                'Kabupaten Tapanuli Selatan',
                'Kabupaten Tapanuli Tengah',
                'Kabupaten Tapanuli Utara',
                'Kabupaten Toba Samosir',
                'Kota Binjai',
                'Kota Gunungsitoli',
                'Kota Medan',
                'Kota Padangsidempuan',
                'Kota Pematangsiantar',
                'Kota Sibolga',
                'Kota Tanjungbalai',
                'Kota Tebing Tinggi',
            ]],

            // Provinsi Sumatera Barat
            ['provinsi' => 'Sumatera Barat', 'kota_kabupaten' => [
                'Kabupaten Agam',
                'Kabupaten Dharmasraya',
                'Kabupaten Kepulauan Mentawai',
                'Kabupaten Lima Puluh Kota',
                'Kabupaten Padang Pariaman',
                'Kabupaten Pasaman',
                'Kabupaten Pasaman Barat',
                'Kabupaten Pesisir Selatan',
                'Kabupaten Sijunjung',
                'Kabupaten Solok',
                'Kabupaten Solok Selatan',
                'Kabupaten Tanah Datar',
                'Kota Bukittinggi',
                'Kota Padang',
                'Kota Padangpanjang',
                'Kota Pariaman',
                'Kota Payakumbuh',
                'Kota Sawahlunto',
                'Kota Solok',
            ]],

            // Provinsi Sumatera Selatan
            ['provinsi' => 'Sumatera Selatan', 'kota_kabupaten' => [
                'Kabupaten Banyuasin',
                'Kabupaten Empat Lawang',
                'Kabupaten Lahat',
                'Kabupaten Muara Enim',
                'Kabupaten Musi Banyuasin',
                'Kabupaten Musi Rawas',
                'Kabupaten Musi Rawas Utara',
                'Kabupaten Ogan Ilir',
                'Kabupaten Ogan Komering Ilir',
                'Kabupaten Ogan Komering Ulu',
                'Kabupaten Ogan Komering Ulu Selatan',
                'Kabupaten Ogan Komering Ulu Timur',
                'Kabupaten Penukal Abab Lematang Ilir',
                'Kota Lubuklinggau',
                'Kota Pagar Alam',
                'Kota Palembang',
                'Kota Prabumulih',
            ]],

            // Provinsi Riau
            ['provinsi' => 'Riau', 'kota_kabupaten' => [
                'Kabupaten Bengkalis',
                'Kabupaten Indragiri Hilir',
                'Kabupaten Indragiri Hulu',
                'Kabupaten Kampar',
                'Kabupaten Kepulauan Meranti',
                'Kabupaten Kuantan Singingi',
                'Kabupaten Pelalawan',
                'Kabupaten Rokan Hilir',
                'Kabupaten Rokan Hulu',
                'Kabupaten Siak',
                'Kota Dumai',
                'Kota Pekanbaru',
            ]],

            // Provinsi Kepulauan Riau
            ['provinsi' => 'Kepulauan Riau', 'kota_kabupaten' => [
                'Kabupaten Bintan',
                'Kabupaten Karimun',
                'Kabupaten Kepulauan Anambas',
                'Kabupaten Lingga',
                'Kabupaten Natuna',
                'Kota Batam',
                'Kota Tanjung Pinang',
            ]],

            // Provinsi Jambi
            ['provinsi' => 'Jambi', 'kota_kabupaten' => [
                'Kabupaten Batanghari',
                'Kabupaten Bungo',
                'Kabupaten Kerinci',
                'Kabupaten Merangin',
                'Kabupaten Muaro Jambi',
                'Kabupaten Sarolangun',
                'Kabupaten Tanjung Jabung Barat',
                'Kabupaten Tanjung Jabung Timur',
                'Kabupaten Tebo',
                'Kota Jambi',
                'Kota Sungai Penuh',
            ]],

            // Provinsi Bengkulu
            ['provinsi' => 'Bengkulu', 'kota_kabupaten' => [
                'Kabupaten Bengkulu Selatan',
                'Kabupaten Bengkulu Tengah',
                'Kabupaten Bengkulu Utara',
                'Kabupaten Kaur',
                'Kabupaten Kepahiang',
                'Kabupaten Lebong',
                'Kabupaten Mukomuko',
                'Kabupaten Rejang Lebong',
                'Kabupaten Seluma',
                'Kota Bengkulu',
            ]],

            // Provinsi Bangka Belitung
            ['provinsi' => 'Bangka Belitung', 'kota_kabupaten' => [
                'Kabupaten Bangka',
                'Kabupaten Bangka Barat',
                'Kabupaten Bangka Selatan',
                'Kabupaten Bangka Tengah',
                'Kabupaten Belitung',
                'Kabupaten Belitung Timur',
                'Kota Pangkal Pinang',
            ]],

            // Provinsi Lampung
            ['provinsi' => 'Lampung', 'kota_kabupaten' => [
                'Kabupaten Lampung Tengah',
                'Kabupaten Lampung Utara',
                'Kabupaten Lampung Selatan',
                'Kabupaten Lampung Barat',
                'Kabupaten Lampung Timur',
                'Kabupaten Mesuji',
                'Kabupaten Pesawaran',
                'Kabupaten Pesisir Barat',
                'Kabupaten Pringsewu',
                'Kabupaten Tulang Bawang',
                'Kabupaten Tulang Bawang Barat',
                'Kabupaten Tanggamus',
                'Kabupaten Way Kanan',
                'Kota Bandar Lampung',
                'Kota Metro',
            ]],

            // Provinsi Banten
            ['provinsi' => 'Banten', 'kota_kabupaten' => [
                'Kabupaten Lebak',
                'Kabupaten Pandeglang',
                'Kabupaten Serang',
                'Kabupaten Tangerang',
                'Kota Cilegon',
                'Kota Serang',
                'Kota Tangerang',
                'Kota Tangerang Selatan',
            ]],

            // Provinsi Jawa Barat
            ['provinsi' => 'Jawa Barat', 'kota_kabupaten' => [
                'Kabupaten Bandung',
                'Kabupaten Bandung Barat',
                'Kabupaten Bekasi',
                'Kabupaten Bogor',
                'Kabupaten Ciamis',
                'Kabupaten Cianjur',
                'Kabupaten Cirebon',
                'Kabupaten Garut',
                'Kabupaten Indramayu',
                'Kabupaten Karawang',
                'Kabupaten Kuningan',
                'Kabupaten Majalengka',
                'Kabupaten Pangandaran',
                'Kabupaten Purwakarta',
                'Kabupaten Subang',
                'Kabupaten Sukabumi',
                'Kabupaten Sumedang',
                'Kabupaten Tasikmalaya',
                'Kota Bandung',
                'Kota Banjar',
                'Kota Bekasi',
                'Kota Bogor',
                'Kota Cimahi',
                'Kota Cirebon',
                'Kota Depok',
                'Kota Sukabumi',
                'Kota Tasikmalaya',
            ]],

            // Provinsi DKI Jakarta
            ['provinsi' => 'DKI Jakarta', 'kota_kabupaten' => [
                'Kota Jakarta Barat',
                'Kota Jakarta Pusat',
                'Kota Jakarta Selatan',
                'Kota Jakarta Timur',
                'Kota Jakarta Utara',
                'Kepulauan Seribu',
            ]],

            // Provinsi Jawa Tengah
            ['provinsi' => 'Jawa Tengah', 'kota_kabupaten' => [
                'Kabupaten Banjarnegara',
                'Kabupaten Batang',
                'Kabupaten Blora',
                'Kabupaten Boyolali',
                'Kabupaten Brebes',
                'Kabupaten Cilacap',
                'Kabupaten Demak',
                'Kabupaten Grobogan',
                'Kabupaten Jepara',
                'Kabupaten Karanganyar',
                'Kabupaten Kebumen',
                'Kabupaten Kendal',
                'Kabupaten Klaten',
                'Kabupaten Kudus',
                'Kabupaten Magelang',
                'Kabupaten Pati',
                'Kabupaten Pekalongan',
                'Kabupaten Pemalang',
                'Kabupaten Purbalingga',
                'Kabupaten Purworejo',
                'Kabupaten Rembang',
                'Kabupaten Semarang',
                'Kabupaten Sragen',
                'Kabupaten Sukoharjo',
                'Kabupaten Tegal',
                'Kabupaten Temanggung',
                'Kabupaten Wonogiri',
                'Kabupaten Wonosobo',
                'Kota Magelang',
                'Kota Pekalongan',
                'Kota Semarang',
                'Kota Surakarta',
                'Kota Tegal',
            ]],

            // Provinsi DIY Yogyakarta
            ['provinsi' => 'DIY Yogyakarta', 'kota_kabupaten' => [
                'Kabupaten Bantul',
                'Kabupaten Gunung Kidul',
                'Kabupaten Kulon Progo',
                'Kabupaten Sleman',
                'Kota Yogyakarta',
            ]],

            // Provinsi Jawa Timur
            ['provinsi' => 'Jawa Timur', 'kota_kabupaten' => [
                'Kabupaten Bangkalan',
                'Kabupaten Banyuwangi',
                'Kabupaten Blitar',
                'Kabupaten Bojonegoro',
                'Kabupaten Bondowoso',
                'Kabupaten Gresik',
                'Kabupaten Jember',
                'Kabupaten Jombang',
                'Kabupaten Kediri',
                'Kabupaten Lamongan',
                'Kabupaten Lumajang',
                'Kabupaten Madiun',
                'Kabupaten Magetan',
                'Kabupaten Mojokerto',
                'Kabupaten Nganjuk',
                'Kabupaten Ngawi',
                'Kabupaten Pacitan',
                'Kabupaten Pamekasan',
                'Kabupaten Ponorogo',
                'Kabupaten Probolinggo',
                'Kabupaten Sampang',
                'Kabupaten Sidoarjo',
                'Kabupaten Situbondo',
                'Kabupaten Sumenep',
                'Kabupaten Trenggalek',
                'Kabupaten Tuban',
                'Kabupaten Tulungagung',
                'Kota Batu',
                'Kota Blitar',
                'Kota Kediri',
                'Kota Madiun',
                'Kota Mojokerto',
                'Kota Pasuruan',
                'Kota Probolinggo',
                'Kota Surabaya',
            ]],

            // Provinsi Bali
            ['provinsi' => 'Bali', 'kota_kabupaten' => [
                'Kabupaten Badung',
                'Kabupaten Bangli',
                'Kabupaten Buleleng',
                'Kabupaten Gianyar',
                'Kabupaten Jembrana',
                'Kabupaten Karangasem',
                'Kabupaten Klungkung',
                'Kabupaten Tabanan',
                'Kota Denpasar',
            ]],

            // Provinsi Nusa Tenggara Barat
            ['provinsi' => 'Nusa Tenggara Barat', 'kota_kabupaten' => [
                'Kabupaten Bima',
                'Kabupaten Dompu',
                'Kabupaten Lombok Barat',
                'Kabupaten Lombok Tengah',
                'Kabupaten Lombok Timur',
                'Kabupaten Lombok Utara',
                'Kabupaten Sumbawa',
                'Kabupaten Sumbawa Barat',
                'Kota Bima',
                'Kota Mataram',
            ]],

            // Provinsi Nusa Tenggara Timur
            ['provinsi' => 'Nusa Tenggara Timur', 'kota_kabupaten' => [
                'Kabupaten Belu',
                'Kabupaten Ende',
                'Kabupaten Flores Timur',
                'Kabupaten Kupang',
                'Kabupaten Lembata',
                'Kabupaten Manggarai',
                'Kabupaten Manggarai Barat',
                'Kabupaten Manggarai Timur',
                'Kabupaten Nagekeo',
                'Kabupaten Ngada',
                'Kabupaten Sikka',
                'Kabupaten Sumba Barat',
                'Kabupaten Sumba Barat Daya',
                'Kabupaten Sumba Tengah',
                'Kabupaten Sumba Timur',
                'Kabupaten Timor Tengah Selatan',
                'Kabupaten Timor Tengah Utara',
                'Kota Kupang',
            ]],

            // Provinsi Kalimantan Barat
            ['provinsi' => 'Kalimantan Barat', 'kota_kabupaten' => [
                'Kabupaten Bengkayang',
                'Kabupaten Kapuas Hulu',
                'Kabupaten Kayong Utara',
                'Kabupaten Ketapang',
                'Kabupaten Kubu Raya',
                'Kabupaten Landak',
                'Kabupaten Melawi',
                'Kabupaten Mempawah',
                'Kabupaten Sambas',
                'Kabupaten Sanggau',
                'Kabupaten Sekadau',
                'Kabupaten Sintang',
                'Kota Pontianak',
                'Kota Singkawang',
            ]],

            // Provinsi Kalimantan Tengah
            ['provinsi' => 'Kalimantan Tengah', 'kota_kabupaten' => [
                'Kabupaten Barito Selatan',
                'Kabupaten Barito Timur',
                'Kabupaten Barito Utara',
                'Kabupaten Gunung Mas',
                'Kabupaten Kapuas',
                'Kabupaten Katingan',
                'Kabupaten Kotawaringin Barat',
                'Kabupaten Kotawaringin Timur',
                'Kabupaten Lamandau',
                'Kabupaten Murung Raya',
                'Kabupaten Palangka Raya',
                'Kabupaten Pulang Pisau',
                'Kabupaten Sukamara',
                'Kabupaten Seruyan',
            ]],

            // Provinsi Kalimantan Selatan
            ['provinsi' => 'Kalimantan Selatan', 'kota_kabupaten' => [
                'Kabupaten Balangan',
                'Kabupaten Banjar',
                'Kabupaten Barito Kuala',
                'Kabupaten Hulu Sungai Selatan',
                'Kabupaten Hulu Sungai Tengah',
                'Kabupaten Hulu Sungai Utara',
                'Kabupaten Kotabaru',
                'Kabupaten Tabalong',
                'Kabupaten Tanah Bumbu',
                'Kabupaten Tanah Laut',
                'Kabupaten Tapin',
                'Kota Banjarbaru',
                'Kota Banjarmasin',
            ]],

            // Provinsi Kalimantan Timur
            ['provinsi' => 'Kalimantan Timur', 'kota_kabupaten' => [
                'Kabupaten Berau',
                'Kabupaten Kutai Barat',
                'Kabupaten Kutai Kartanegara',
                'Kabupaten Kutai Timur',
                'Kabupaten Mahakam Ulu',
                'Kabupaten Paser',
                'Kabupaten Penajam Paser Utara',
                'Kota Balikpapan',
                'Kota Bontang',
                'Kota Samarinda',
            ]],

            // Provinsi Kalimantan Utara
            ['provinsi' => 'Kalimantan Utara', 'kota_kabupaten' => [
                'Kabupaten Bulungan',
                'Kabupaten Malinau',
                'Kabupaten Nunukan',
                'Kabupaten Tana Tidung',
                'Kota Tarakan',
            ]],

            // Provinsi Sulawesi Utara
            ['provinsi' => 'Sulawesi Utara', 'kota_kabupaten' => [
                'Kabupaten Bolaang Mongondow',
                'Kabupaten Bolaang Mongondow Selatan',
                'Kabupaten Bolaang Mongondow Timur',
                'Kabupaten Bolaang Mongondow Utara',
                'Kabupaten Minahasa',
                'Kabupaten Minahasa Selatan',
                'Kabupaten Minahasa Tenggara',
                'Kabupaten Minahasa Utara',
                'Kabupaten Sangihe',
                'Kabupaten Siau Tagulandang Biaro',
                'Kabupaten Kepulauan Sangihe',
                'Kota Bitung',
                'Kota Manado',
                'Kota Tomohon',
            ]],

            // Provinsi Sulawesi Tengah
            ['provinsi' => 'Sulawesi Tengah', 'kota_kabupaten' => [
                'Kabupaten Banggai',
                'Kabupaten Banggai Kepulauan',
                'Kabupaten Buol',
                'Kabupaten Donggala',
                'Kabupaten Morowali',
                'Kabupaten Morowali Utara',
                'Kabupaten Parigi Moutong',
                'Kabupaten Poso',
                'Kabupaten Tojo Una-Una',
                'Kota Palu',
            ]],

            // Provinsi Sulawesi Selatan
            ['provinsi' => 'Sulawesi Selatan', 'kota_kabupaten' => [
                'Kabupaten Bantaeng',
                'Kabupaten Barru',
                'Kabupaten Bone',
                'Kabupaten Bulukumba',
                'Kabupaten Enrekang',
                'Kabupaten Gowa',
                'Kabupaten Jeneponto',
                'Kabupaten Luwu',
                'Kabupaten Luwu Timur',
                'Kabupaten Luwu Utara',
                'Kabupaten Maros',
                'Kabupaten Pangkep',
                'Kabupaten Pinrang',
                'Kabupaten Selayar',
                'Kabupaten Sidenreng Rappang',
                'Kabupaten Sinjai',
                'Kabupaten Soppeng',
                'Kabupaten Takalar',
                'Kabupaten Tana Toraja',
                'Kabupaten Toraja Utara',
                'Kota Makassar',
                'Kota Parepare',
                'Kota Palopo',
            ]],

            // Provinsi Sulawesi Tenggara
            ['provinsi' => 'Sulawesi Tenggara', 'kota_kabupaten' => [
                'Kabupaten Buton',
                'Kabupaten Buton Selatan',
                'Kabupaten Buton Tengah',
                'Kabupaten Buton Utara',
                'Kabupaten Kolaka',
                'Kabupaten Kolaka Timur',
                'Kabupaten Kolaka Utara',
                'Kabupaten Konawe',
                'Kabupaten Konawe Kepulauan',
                'Kabupaten Konawe Selatan',
                'Kabupaten Konawe Utara',
                'Kabupaten Muna',
                'Kabupaten Wakatobi',
                'Kota Bau-Bau',
                'Kota Kendari',
            ]],

            // Provinsi Gorontalo
            ['provinsi' => 'Gorontalo', 'kota_kabupaten' => [
                'Kabupaten Boalemo',
                'Kabupaten Bone Bolango',
                'Kabupaten Gorontalo',
                'Kabupaten Gorontalo Utara',
                'Kabupaten Pohuwato',
                'Kota Gorontalo',
            ]],

            // Provinsi Maluku
            ['provinsi' => 'Maluku', 'kota_kabupaten' => [
                'Kabupaten Buru',
                'Kabupaten Buru Selatan',
                'Kabupaten Maluku Barat Daya',
                'Kabupaten Maluku Tengah',
                'Kabupaten Maluku Tenggara',
                'Kabupaten Maluku Tenggara Barat',
                'Kabupaten Seram Bagian Barat',
                'Kabupaten Seram Bagian Timur',
                'Kota Ambon',
            ]],

            // Provinsi Maluku Utara
            ['provinsi' => 'Maluku Utara', 'kota_kabupaten' => [
                'Kabupaten Halmahera Barat',
                'Kabupaten Halmahera Tengah',
                'Kabupaten Halmahera Timur',
                'Kabupaten Halmahera Utara',
                'Kabupaten Halmahera Selatan',
                'Kabupaten Kepulauan Sula',
                'Kabupaten Pulau Morotai',
                'Kabupaten Pulau Taliabu',
                'Kota Ternate',
                'Kota Tidore Kepulauan',
            ]],

            // Provinsi Papua Barat
            ['provinsi' => 'Papua Barat', 'kota_kabupaten' => [
                'Kabupaten Fakfak',
                'Kabupaten Kaimana',
                'Kabupaten Manokwari',
                'Kabupaten Maybrat',
                'Kabupaten Pegunungan Arfak',
                'Kabupaten Raja Ampat',
                'Kabupaten Sorong',
                'Kabupaten Tambrauw',
                'Kabupaten Teluk Bintuni',
                'Kabupaten Teluk Wondama',
                'Kota Sorong',
            ]],

            // Provinsi Papua
            ['provinsi' => 'Papua', 'kota_kabupaten' => [
                'Kabupaten Asmat',
                'Kabupaten Biak Numfor',
                'Kabupaten Boven Digoel',
                'Kabupaten Deiyai',
                'Kabupaten Dogiyai',
                'Kabupaten Intan Jaya',
                'Kabupaten Jayapura',
                'Kabupaten Jayawijaya',
                'Kabupaten Keerom',
                'Kabupaten Mamberamo Raya',
                'Kabupaten Mamberamo Tengah',
                'Kabupaten Nduga',
                'Kabupaten Paniai',
                'Kabupaten Puncak',
                'Kabupaten Puncak Jaya',
                'Kabupaten Supiori',
                'Kabupaten Tolikara',
                'Kabupaten Yahukimo',
                'Kabupaten Yalimo',
                'Kabupaten Yapen',
                'Kota Jayapura',
            ]],
        ];

        foreach ($regions as $entry) {
            $provinsi = $entry['provinsi'];
            foreach ($entry['kota_kabupaten'] as $kota_kabupaten) {
                DB::table('regions')->insert([
                    'provinsi' => $provinsi,
                    'kota_kabupaten' => $kota_kabupaten
                ]);
            }
        }
    }
}
